export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR';

export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';

export const FETCH_DELETE_ERROR = 'FETCH_DELETE_ERROR';

export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_ERROR = 'FETCH_TASK_ERROR';

export const TOGGLE_FAVORITES_SUCCESS = 'TOGGLE_FAVORITES_SUCCESS';

export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';

