export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_ALL_TASKS = 'FETCH_ALL_TASKS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR';
export const ADD_TASK = 'ADD_TASK';
export const FETCH_NEW_STATE = 'FETCH_NEW_STATE';

